version: "3.9"

services:
  backend:
    container_name: backend
    image: backend
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "7000:7000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
